### ISSUE TITLE
[Feature Request] Add Support for Debugging

### ISSUE THREAD

**Issue by RoyiAvital** [mathworks/MATLAB-extension-for-vscode#103]
Please add the ability to debug files and run using Debug mode:

1. Set breakpoints.
2. Set conditional breakpoints.
3. Variable Viewer.

**Comment by mwickert** [comment]
A step this direction be to provide a button to open the MATLAB code editor (as found in the extension **Matlab in VSCode**). With this intermediate level of support you run code from vs code that then jumps to break points set in the MATLAB code editor.

**Comment by Gusmano-2-OSU** [comment]
I know this would be a huge ask, but introducing [Logpoints](https://code.visualstudio.com/blogs/2018/07/12/introducing-logpoints-and-auto-attach) would be really helpful for debugging!

**Comment by mwickert** [comment]
@Gusmano-2-OSU I looked at the log points discussion and agree that debugging is more than setting break points. Improper changes in state over time are critical to resolving broken algorithms.

**Comment by Lucas-Polo** [comment]
I endorse this request.

For any real project, having the ability to debug the code is an unavoidable need. Therefore, it would be extremely practical being able to do so from the VS Code environment.

**Comment by spacemanjosh** [comment]
+1 for breakpoints and variable view.  I'm loving the editor, but without breakpoints it makes it very difficult to debug.  That said, I love the VSCode integration overall.

**Comment by fspinar** [comment]
+1

Using VS code matlab extension changed my life, I loved it, except that to be able to use the debugging features I need t run matlab and VS code together... Please add those features !

**Comment by bblockwood** [comment]
+1 

This would be a very valuable addition, and would be the last step for making this a fully usable matlab editing solution for me.

**Comment by homecls** [comment]
+1

**Comment by jarleppa** [comment]
This is definitely a necessity for utilizing MATLAB in VS Code environment. At least breakpoint support would be the first step towards improving the usability of the addon.

**Comment by nadlechSICKAG** [comment]
+1

**Comment by alfredohernandezinostroza** [comment]
+1

**Comment by witty-one** [comment]
+1! Absolute must!!!

**Comment by gledsonrt** [comment]
+1

**Comment by theDanishCG** [comment]
Here to say that I would absolutely love if I could at least review variables after a run.

**Comment by cuixing158** [comment]
+1
