### ISSUE TITLE
cannot run Matlab after installation of extension: you dont have an extension for debugging Matlab

### ISSUE THREAD

**Issue by sedy2014** [mathworks/MATLAB-extension-for-vscode#11]
I followed the steps here:
MATLAB extension for Visual Studio Code
my setting are:
![image](https://user-images.githubusercontent.com/9708680/235999637-f9992750-5234-472e-aa19-04ecf71eb243.png).
![image](https://user-images.githubusercontent.com/9708680/236000007-61c05c63-9b76-4ec9-b87c-3784e363cc26.png)

When i try to run matlab, I get:
![image](https://user-images.githubusercontent.com/9708680/235999778-e47f9a54-f4ee-4fd3-94b2-c86e967508ee.png)

How do i resolve this?

sedy

**Comment by dklilley** [comment]
> When i try to run matlab, I get:

Can you clarify what you mean about running MATLAB?

**Comment by sedy2014** [comment]
basically, just put breakpoint and debug or even Run to a line.

**Comment by sedy2014** [comment]
Ok,that is a bummer. In that case, it should be better to rename extension as Matlab Editor and not Matlab and have this specified as the opening statement, so that people dont spend hours searching about debugging for ways to run it.

**Comment by FriedrichTuttas** [comment]
It is great to hear that it is planned to implement code execution and debugging from within VS Code. @toshiakit is there a schedule for when us users can expect those functionalities?

**Comment by toshiakit** [comment]
Thank you for your feedback and I passed it along to the development team. They are currently working on these enhancements, but they don't have a definite timeline for the release yet.

**Comment by dklilley** [comment]
Closing this as a duplicate of #4
