### ISSUE TITLE
MATLAB (Intel installation) fails to connect on Apple Silicon system

### ISSUE THREAD

**Issue by sohaildasgupta** [mathworks/MATLAB-extension-for-vscode#110]
I installed the MATLAB extension for VSCode on macOS. However, I cannot run any MATLAB script. It opens a new terminal and blanks out.

I also observe that in the bottom panel it shows "MATLAB: Not Connected". If I click on it and try to "Connect to MATLAB", nothing happens. My MATLAB path is correct. I tried re-installing with no success. I am using MATLAB version R2023B.

**Comment by dklilley** [comment]
Thanks for reporting this!

In the Output panel in VS Code (selecting "MATLAB Language Server" from the dropdown), a log directory is printed. Please share the log files within this directory.

**Comment by sohaildasgupta** [comment]
I should point out that I tried the extension with the R2024a pre-release. IT WORKS as is!
Could it be just a version issue? I haven't tried with other version.

**Comment by Snaptraks** [comment]
I had this exact problem, and my MATLAB window would hang forever, and the log directory would be essentially empty, except for one file with the only two lines:

(08:53:49) matlabls: Log Directory: C:\Users\Username\AppData\Local\Temp\matlabls_7652
(10:06:57) matlabls: Launching MATLAB...

I fixed it by NOT using the New Desktop feature, now VS Code connects quickly to MATLAB and I do not have errors saying that "This feature is not available without MATLAB running."

I hope this can narrow down the issue and provides a workaround for now

**Comment by dklilley** [comment]
@sohaildasgupta - a few clarifying questions -

* What version of the extension do you have installed?
* What architecture is your Mac (maca64 or maci64)?
* Do you have any problems launching R2023b normally?
* If you navigate to the same directory for your R2024a pre-release installation, do you see a `maci64` or a `maca64` directory?

This strikes me as an issue with the MATLAB installation.

**Comment by peoe** [comment]
Sorry to chime in on this conversation, but I would like to support @Snaptraks argument with a similar experience:

I installed 2024a (24.1.0.2537033) today using the Apple Silicon installer, enabled the new desktop after launch, and correctly updated my install path but Matlab would just not connect. After going back and disabling the new desktop the connection occurs pretty rapidly and I can run scripts using the "Run File" command no problem.

**Comment by hamidingit** [comment]
Thanks for your feedback and continuous usage of our extension!
just to clarify, if you have connection issues and using our extension with the "New MATLAB Desktop", please refer to https://github.com/mathworks/MATLAB-extension-for-vscode/issues/24 for the latest status.

**Comment by pdgradney** [comment]
I am having a similar issue running matlab version 2023a on my mac, the difference is I am running the intel version of matlab.   I have a program that can only communicate with matlab via the intel version, as a result I can not run the arm version of matlab.  Is there a way to get the vs code extension to work on an M2 mac using the intel version of matlab?

**Comment by yanikschwab** [comment]
The Intel Version of MATLAB works, if you use a MATLAB Version that was released before the arm specific version (MATLAB_R2023a).
