### ISSUE TITLE
tlc support

### ISSUE THREAD

**Issue by SpieringsAE** [mathworks/MATLAB-extension-for-vscode#115]
I work a lot with tlc files related to level 2 s functions, but working with them can be a bit of a hassle, there is one plugin for it that already exists but its very lacking in functionality.

It would be great if someone who actually knows the intrinsics (so mathworks) could provide proper support for it.

**Comment by nickchoi-mw** [comment]
Thanks for the feedback! To better understand your workflow, can you provide some more information regarding how editing TLC files fits into your overall workflow in VS Code? 

In any case, this is definitely an enhancement request that we will pass along to the teams that develop the TLC and S-Function infrastructure for generating code from Simulink models. I am going to create the enhancement request internally with those teams to consider for a potential future release and will close this issue. The internal request will point to this issue so please feel free to add any additional feedback here.

**Comment by SpieringsAE** [comment]
Thank you for the response, I hope it turns out to become something.
I help maintain an open source blockset for a set of embedded linux controllers [here](https://github.com/GOcontroll/GOcontroll-Simulink/tree/2023b). (tlcs can be found in blockset/blocks)
To interface with the hardware I use s-functions as they allow me to write the c code necessary for it. I think it will probably be difficult to get very tight integration, but having linting for the tlc directives would already be a great help.

**Comment by nickchoi-mw** [comment]
Thanks for sharing more info on your workflow!
