### ISSUE TITLE
Instance renaming a la Shift + Enter

### ISSUE THREAD

**Issue by Tastaturtaste** [mathworks/MATLAB-extension-for-vscode#12]
In the Matlab editor it is possible to rename instances of a variable by changing the name at one place and hitting Shift + Enter. Other lsp's I use for other languages provide the ability to select an identifier, hit F2 and enter a new name in a popup. I think this second approach is more natural and I would like to see this Matlab extension support this. This could also automatically rename the files of classes and functions if the class or function gets renamed to conform to Matlabs expectations of coherence.

**Comment by dklilley** [comment]
Missed this issue - this is now supported as of v1.2.5 (#173)
