### ISSUE TITLE
Cannot connect to MATLAB 2024a on mac Sonoma 14.4.1

### ISSUE THREAD

**Issue by afugls** [mathworks/MATLAB-extension-for-vscode#127]
**Describe the bug**
MATLAB was unable to start. 
MATLAB is installed and the MATLAB executable path setting is properly configured.

**To Reproduce**
1. Go to 'vs code', open the workspace folder
2. Click on 'Connect to MATLAB'
3. Notification prompts: MATLAB was unable to start. If MATLAB is installed, confirm that the MATLAB executable path setting is properly configured

**Expected behavior**
VS Code should connect to MATLAB.

**Screenshots**
Pop up message:
<img width="462" alt="Skærmbillede 2024-04-04 kl  11 27 17" src="https://github.com/mathworks/MATLAB-extension-for-vscode/assets/31472302/87354e52-eee6-4070-b072-ae10af148c43">

**Useful Information**
 - OS Version: mac os Sonoma 14.4.1
 - VS Code Version: 1.87.2
 - MATLAB Version: R2024a

**Additional context**
MATLAB root: `/Applications/MATLAB_R2024a.app`

MATLAB extension settings:
<img width="1012" alt="Skærmbillede 2024-04-04 kl  11 28 18" src="https://github.com/mathworks/MATLAB-extension-for-vscode/assets/31472302/e2959fbb-da91-4e86-a031-b9656380f4dc">

**Output log**
```
(11:11:15) matlabls: Launching MATLAB...
[Error - 11.11.15] (11:11:15) matlabls - ERROR: Error launching MATLAB: spawn /Applications/MATLAB_2024a.app/bin/matlab ENOENT
[Error - 11.11.15] (11:11:15) matlabls - ERROR: Error launching MATLAB: Error
[Error - 11.11.15] (11:11:15) matlabls - ERROR: Error launching MATLAB: Error: spawn /Applications/MATLAB_2024a.app/bin/matlab ENOENT
    at Process.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(11:11:15) matlabls: MATLAB process terminated
```

**Comment by dklilley** [comment]
Hi @afugls , thanks for raising this!

At the beginning of the output panel for the language server in VS Code, a log directory should be printed. Can you please share the logs in that location? This will help us narrow this issue down.

**Comment by afugls** [comment]
Thank you! Installing the MATLAB Apple Silicon solved the issue. 
I never realized I had installed the Intel version before.
