### ISSUE TITLE
Vscode doesnt recognize matlab code files

### ISSUE THREAD

**Issue by Fuzqui** [mathworks/MATLAB-extension-for-vscode#134]
Hello,

I have installed the matlab extension on vscode. The connection works and I can run matlab code through the matlab terminal on vscode. But I don't have the run button, the highlighted syntax and all the features of the extension, it is as if vscode doesnt recognize the file as a matlab code file.

thanks for your help
<img width="1391" alt="Capture d’écran 2024-04-15 à 21 19 05" src="https://github.com/mathworks/MATLAB-extension-for-vscode/assets/165004407/5cd34da2-a671-4533-9baa-e2d4108c609f">

**Comment by dklilley** [comment]
Hi @Fuzqui , can you please let us know what language VS Code believes the file to be? This should display in the status bar, typically in the bottom right part of the window.

**Comment by Fuzqui** [comment]
you are right, I had the octave debugger ! it works now. thanks a lot !!!!
