### ISSUE TITLE
No code-folding on functions or comment blocks and more

### ISSUE THREAD

**Issue by anakinsleftleg** [mathworks/MATLAB-extension-for-vscode#14]
Code folding is very limited (I don't even see where it's available) and especially not available for comment blocks or functions.

**Comment by dklilley** [comment]
Code folding should be available for these kinds of block statements - you will need to hover the mouse over the left margin for the folding arrows to appear:

![image](https://user-images.githubusercontent.com/12896371/236452835-ce873f1f-84c0-4c7a-9547-2fa4cd65234a.png)

![image](https://user-images.githubusercontent.com/12896371/236453001-328a48a1-7990-4acf-9afe-17ed5fcbd493.png)

**Comment by anakinsleftleg** [comment]
When i hover over the gutter, those arrows don't appear. They do in other languages though.

![image](https://user-images.githubusercontent.com/77084568/236542785-dedcc7a6-83e5-4e22-818e-eaecec103ea6.png)

**Comment by anakinsleftleg** [comment]
It's my mistake, or actually, an extension's mistake. The extension Better Folding was conflicting and causing both of my issues to be problems in Matlab files. I disabled it and both issues are resolved. Thank you.
