### ISSUE TITLE
MATLAB is killing my machines with GitHub!!

### ISSUE THREAD

**Issue by C-Nuteras** [mathworks/MATLAB-extension-for-vscode#146]

**Comment by dklilley** [comment]
Hi @C-Nuteras , thanks for reaching out about this!

Here are a few questions which might help narrow this down:
1. Can you describe your setup? I'm not sure what you mean by GitHub being integrated.
2. Are you able to share the code which is causing this crash?
3. Does the crash reproduce when running the code within MATLAB directly (not VS Code)?

**Comment by dklilley** [comment]
It looks like you deleted the description of this issue. Is this still something you would like assistance with?
