### ISSUE TITLE
Add bold highlights for section name comments `%%`

### ISSUE THREAD

**Issue by wohenbushuang** [mathworks/MATLAB-extension-for-vscode#150]
**Is your feature request related to a problem? Please describe.**
if you comment with `%%` in the begining of lines, Matlab editor will recognize it as a section divider, and mark the comment line with bold font. But in vscode there is no visual difference, and thus I find it hard to quickly locate the beginnings of different sections.

**Describe the solution you'd like**
As in Matlab editor does, make the comment line bold. Or highlight it with some bright colors, as other comment extensions of vscode does ([Eg. better commments](https://marketplace.visualstudio.com/items?itemName=aaron-bond.better-comments)).

**Additional context**
![image](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/15613184/09dbe3e7-15d7-41b7-9d2e-cf768ac06f5a)
![image](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/15613184/55ed54a5-527a-4710-abad-482a8404d0c3)

**Comment by dklilley** [comment]
Thanks for the request!

Note: This may be related to #69

**Comment by wohenbushuang** [comment]
This issue is duplicated with #69.
