### ISSUE TITLE
Opening figures from vscode

### ISSUE THREAD

**Issue by DFriend01** [mathworks/MATLAB-extension-for-vscode#156]
**Is your feature request related to a problem? Please describe.**
Opening figures from the VS Code UI does not seem to be something that is currently supported. Opening the figure outside VS Code, in my experience, requires me to close VS Code so the MATLAB session is freed. A solution that does not require closing VS Code while leveraging the UI is desired.

**Describe the solution you'd like**
An option to open a figure from a context menu by right-clicking on a `.fig` file from the file explorer would be a nice solution, much like how adding files/folders to the MATLAB path works for the extension right now. The figure should open in a separate window.

**Describe alternatives you've considered**
I currently do the following to open a `.fig` file from VS Code:
1. Right-click the `.fig` file that I want to open
2. Select "Copy Path" from the context menu
3. Open the MATLAB terminal, call the `openfig` function, and paste the copied path in as an argument to the function

**Comment by Achuan-2** [comment]
Look forward to improvement
