### ISSUE TITLE
Compatibility with Matlab <2021

### ISSUE THREAD

**Issue by Lebsasha** [mathworks/MATLAB-extension-for-vscode#17]
Is it planned for the extension to work in some "compatibility" mode with Matlab versions older than 2021, although with some limitations, or these versions will be unsupported at all?

Or, maybe, do you planning to decrease minimum required version of Matlab to, say, 2017?

**Comment by hamidingit** [comment]
Thanks for trying our extension!

We don't have immediate plans to support this as it is noted by @dklilley
