### ISSUE TITLE
Ability to add folders and subfolders to path

### ISSUE THREAD

**Issue by maucejo** [mathworks/MATLAB-extension-for-vscode#171]
Hi all,

First of all, thank you for this extension. For making all my files accessible, I generally use the UI to add folders and subfolders to the path by using a right-click on the considered folder -> "Add to Path" -> "Selected Folders and Subfolders".

Of course, I can always add a `addpath(genpath(...)`, but using the UI is very convenient.

Currently, the Vscode extension allows add only one folder by right-clicking on it. So, it would great to add the subfolders recursively as in the Matlab desktop app.

Thank you.

**Comment by dklilley** [comment]
This context menu option has been added in [v1.2.5](https://github.com/mathworks/MATLAB-extension-for-vscode/pull/173).
