### ISSUE TITLE
Open Simulink Model from VS Code File Explorer

### ISSUE THREAD

**Issue by Gusmano-2-OSU** [mathworks/MATLAB-extension-for-vscode#181]
It would be convenient to be able to open a Simulink model from VS Code's file explorer. Specifically, attempting to open an slx file wouldn't yield the following picture,
![image](https://github.com/user-attachments/assets/6fb131cf-7bff-4de9-9afe-86c9e6896329)
but instead open the model in Simulink.

**Describe alternatives you've considered**
Of course, you can do this from the normal MATLAB UI, but it seems like you'd need to have a separate instance of MATLAB running.

**Comment by dklilley** [comment]
I have marked this closed with the release of v1.3.0. As part of this update, an option has been added to the Explorer context menu to open the selected file in MATLAB. For example, right-click on an SLX file and select "MATLAB: Open File" should result in the file being opened in Simulink via the connected MATLAB instance.

Please feel free to reopen this issue if you feel it isn't adequately addressed.
