### ISSUE TITLE
support the supports .mlx (MATLAB Live Script)

### ISSUE THREAD

**Issue by jiahaoxiang2000** [mathworks/MATLAB-extension-for-vscode#184]
**Is your feature request related to a problem? Please describe.**

I want to run MATLAB code like Python code on Jupyter Notebook. I find that the editor supports .mlx files, but there is no support for it in VS Code.

**Describe the solution you'd like**

Enable the VS Code plugin to support .mlx files.

**Describe alternatives you've considered**

N/A

**Additional context**

I understand that this might be challenging, but I hope someone can work on it. Thank you for considering this request.

**Comment by dklilley** [comment]
Thank you for this request!

I believe that we are currently tracking this request in #71, so I am going to close this as a duplicate for now.

If #71 is not the same as your request, please feel free to comment and this can be reopened.

**Comment by Achuan-2** [comment]
Looking forward to it
