### ISSUE TITLE
Publish extenison to open-vsx.org

### ISSUE THREAD

**Issue by oren-weiss** [mathworks/MATLAB-extension-for-vscode#19]
Hello,

I was wondering if it would be possible to publish this extension to the open-vsx marketplace? See [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by dklilley** [comment]
Thanks for the suggestion! I will discuss this with our team.

**Comment by jeanp413** [comment]
@dklilley Any update on this 🙏

**Comment by oren-weiss** [comment]
@jeanp413 As a work-around, if you want to install this on a VSCode like editor (e.g. VSCodium) you can go to the [version history on VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=MathWorks.language-matlab), download the vsix file, and install manually.

**Comment by dklilley** [comment]
Sorry for the delay in getting back to this thread.

We do not currently plan to publish the extension to the open-vsx marketplace, but we will consider this for a potential future release of the extension.

It sounds like @oren-weiss 's suggestion may be a good alternative for the meantime.
