### ISSUE TITLE
Create "Evaluate Selection in MATLAB Terminal" feature

### ISSUE THREAD

**Issue by mjschroeder** [mathworks/MATLAB-extension-for-vscode#195]
In MATLAB, you can right-click on a selection and use the "Evaluate Selection in Command Window" option from the context menu to execute the selected code.

Right now, the only similar option in VS Code is "Evaluate in Debug Console", which executes the code in the VS console and not in the MATLAB terminal (which throws a suitable warning).

I suggest adding the option for "Evaluate Selection in MATLAB Terminal". Bonus points for assigning F9 as the keyboard shortcut to mimic MATLAB (I think F9 is already assigned, so some other single-key shortcut would be okay).

MATLAB behavior:

![Screenshot 2024-12-19 071812](https://github.com/user-attachments/assets/5f35d565-1148-4fac-80db-a37dbe95c007)

VS Code Behavior: 

![Screenshot 2024-12-19 070912](https://github.com/user-attachments/assets/5642d1bd-969d-4be3-93dc-5c5f8636a4c5)

![Screenshot 2024-12-19 070941](https://github.com/user-attachments/assets/54e42a54-1a7e-4720-a365-50c52d6d611f)

**Comment by guger** [comment]
I'm not sure in which version of the extension this feature was introduced, but there is a "MATLAB: Run current selection" in the context menu that does exactly what you're looking for:
<img width="291" alt="image" src="https://github.com/user-attachments/assets/4d5193c8-cd80-4e05-9b0e-e15582907655" />

**Comment by mjschroeder** [comment]
I'm certain I was running the latest version when I wrote this issue, but the feature I requested is now available. I'm closing the issue.

Great work on this VS Code extension! Keep it up!

![image](https://github.com/user-attachments/assets/a6497c81-d29b-4154-8983-87238d716efd)
