### ISSUE TITLE
QuickOpenNavigate ("Ctrl + P") should allow searching and jumping to symbols

### ISSUE THREAD

**Issue by Tastaturtaste** [mathworks/MATLAB-extension-for-vscode#23]
When typing "Ctrl + P" in VSCode a search bar pops up which allows you to type in a file name and jump to that file with enter. In addition, one can type "@<symbol name>" to jump to that symbol. A symbol could be a type, function, or method name. 

This does not work with the current version of the extension and I would like it to. It makes navigating large files or projects very convenient.

**Comment by rlivings39** [comment]
https://github.com/mathworks/MATLAB-language-server/pull/1 will provide the `@` symbol search support.

**Comment by dklilley** [comment]
This functionality should be present now, and will be released as an update to the extension soon.

**Comment by dklilley** [comment]
This functionality should be present now, and will be released as an update to the extension soon.
