### ISSUE TITLE
Section folding

### ISSUE THREAD

**Issue by gohma231** [mathworks/MATLAB-extension-for-vscode#27]
In MATLAB, sections (denoted by `%%` ) can be folded to improve code navigation and readability. Can this be added to the VSCode extension?

**Comment by dklilley** [comment]
Thanks for raising this! We will consider adding this functionality.

**Comment by dklilley** [comment]
Missed closing this issue. This functionality was added to the extension in v1.2.4, and requires MATLAB R2024b or later.
