### ISSUE TITLE
Definition jumps to local functions that should not be able to be referenced

### ISSUE THREAD

**Issue by wattah1002** [mathworks/MATLAB-extension-for-vscode#31]
`localFunction()` is a local function that can only be referenced in `someFunction()`.
 it should not be referenced in `main.m`, but you can jump to its definition.

I think the error should be shown, but even MATLAB editor does not show it, so if you could at least prevent me from jumping to the definition, it would help prevent the bug.

<img width="1439" alt="image" src="https://github.com/mathworks/MATLAB-extension-for-vscode/assets/62461295/e642a46c-c5f8-40d4-b4c8-0755ec56b8c5">

**Comment by dklilley** [comment]
This should be resolved in v1.1.1.
