### ISSUE TITLE
Quick Fix doesn't work via keyboard shortcut

### ISSUE THREAD

**Issue by michellehirsch** [mathworks/MATLAB-extension-for-vscode#35]
When mousing over code with a code analyzer issue, there's a dialog under the message that offers to View Problem or Quick Fix ...

Clicking on Quick Fix gives a menu that lets me choose to fix or ignore the issue. That's good.

I expected the keyboard shortcut ("Command ." on Mac) do the same thing, but instead it just shows a tooltip saying "No code actions available"

**Comment by dklilley** [comment]
Hi Michelle,
When using the keyboard shortcut for Quick Fix, VS Code checks for any code analyzer issues next to your cursor. If the cursor is not next to a code analyzer info/warning/error, it should report the "No code actions available". Can you confirm that this is the behavior you are seeing?

**Comment by michellehirsch** [comment]
Thanks. That's the behavior I'm seeing. I didn't realize VS code worked this way. 

Here's what I was doing when I created this issue: I leave my cursor where it is and put my mouse over the squiggle to see the message. Then I try using the keyboard shortcut to fix the issue or see the issue.

**Comment by dklilley** [comment]
Closing this issue, as this is VS Code's inherent behavior
