### ISSUE TITLE
"View Problem" jumps to first code issue

### ISSUE THREAD

**Issue by michellehirsch** [mathworks/MATLAB-extension-for-vscode#36]
When mousing over code with a code analyzer issue, there's a dialog under the message that offers to View Problem or Quick Fix ...

Clicking on View Problem (or using the keyboard shortcut) jumps to the first issue in the file. I'm not positive what View Problem is meant to do, but that's not what I expected. I was expecting more detail - maybe an extended code analyzer message, a doc link, or more info in the Problems panel.

**Comment by dklilley** [comment]
Hi Michelle,

I believe that, when using the keyboard shortcut for "View Problem", VS Code tries to apply it to the code analyzer issue at the cursor's location. If the cursor is not at the location of the code analyzer issue, then it jumps to the first message in the document. Can you confirm that this is the behavior you are seeing?

This action should cause VS Code to enter a mode where you can see the info/warning/error text within the document and navigate between messages, like the following:
![image](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/12896371/3f7a7af1-c689-4c04-95eb-8afeab9c6fe0)

**Comment by dklilley** [comment]
Closing this issue, as this is VS Code's inherent behavior
