### ISSUE TITLE
Can we run matlab files in vscode, when matlab is connected in background ?

### ISSUE THREAD

**Issue by burakkurtt** [mathworks/MATLAB-extension-for-vscode#4]

**Comment by mikecroucher** [comment]
No. This is mentioned in the section 'What's missing from this release?' of the blog post. https://blogs.mathworks.com/matlab/2023/04/26/do-you-use-visual-studio-code-matlab-is-now-there-too/ 

Such things are on the radar for future releases though.

**Comment by nwad123** [comment]
Hello!

I reached out to support and they directed me to put my request in this thread. If this is the wrong spot or I'm doing this incorrectly please let me know how I can fix it!

I have seen that there is no support for VS Codes "run and debug" functionality as well as no support for a built-in MATLAB console (for VS code or other applications). I would like to make a feature request of these two items (although it appears they are already in the pipeline). Here is the functionality I would like to see:

1. MATLAB Command line interface:
The ability to interact with MATLAB from the command line. Ideally in VS Code this would be a command or built in terminal option that just acted as a front end to MATLAB. I'm basically imagining the "command window" from the MATLAB GUI just redirected to stdout/err/in. I would love to see the ability to do this from any shell, such as through bash or PowerShell, perhaps with a new flag such as "MATLAB -cli" or "MATLAB -commandlineinterface"

2. Run and debug
I think VS Codes run and debug functionality would naturally build off the command line interface. I envision being able to set up a launch.json file with different MATLAB commands. For example, if I was working on a project that had a GUI, and the GUI was in a separate class from multiple functions, I would like to be able to set up different launch profiles to test the functions or launch the GUI. Adding breakpoints, as well as the option to step through the code would be great as well!

Overall I am so happy with MATLAB, thank you for the work you do!

**Comment by pglira** [comment]
Can you suggest in the meantime a workaround for executing matlab scripts (without debugging) in vscode? I'm currently:

1. starting matlab in a terminal with "matlab -nosplash -nodesktop"
2. manually: cd 'path/to/script' (typically just once)
3. manually: script_filename (multiple times)

Do you know an option to automatize at least steps 2 and 3?

**Comment by hildebrandecon** [comment]
My approach: 

- In VS code, open the file and a terminal
- in the terminal, start MATLAB
- in the matlab file, select the code you want to run and run the VS Code command `Terminal: Run Selected Text In Active Terminal`, this should send your matlab file to the terminal and execute the code there.

Tip: you can define a shortcut for the VS code command!

**Comment by dklilley** [comment]
Execution of MATLAB code is now available! Just update your extension to v1.2.0 to try it out!

You can read more about this in @mikecroucher's [blog post](https://blogs.mathworks.com/matlab/2024/03/05/matlab-extension-for-visual-studio-code-now-with-code-execution/)!
