### ISSUE TITLE
Failed connection to MATLAB despite setting correct exec path

### ISSUE THREAD

**Issue by OofMon2301** [mathworks/MATLAB-extension-for-vscode#47]
Having installed MATLAB on the right path, VSCode still outputs this error:

![image](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/114561394/29087ab6-381c-4d71-a985-9344240a28bc)

The executable path was found by typing `matlabroot` into the desktop app:

![image](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/114561394/ff095dd5-aeb9-4dd5-9856-7b53e2961c21)

The executable path written in VSCode is as follows:

![image](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/114561394/172ca4a8-314e-40cd-bb7b-286983252dd6)

**Comment by dklilley** [comment]
The setting should just be wet to the file path (i.e. `C:\Program Files\MATLAB\R2023a` without quotes).

We will see what we can do to make the README a bit more clear about this.

**Comment by OofMon2301** [comment]
> The setting should just be wet to the file path (i.e. `C:\Program Files\MATLAB\R2023a` without quotes).

Right, that makes sense now. Thank you for the help.
