### ISSUE TITLE
"Go to Definition" does not seem to work when using package folders

### ISSUE THREAD

**Issue by AdamCooman** [mathworks/MATLAB-extension-for-vscode#5]
I like to use [package folders](https://nl.mathworks.com/help/matlab/matlab_oop/scoping-classes-with-packages.html) to keep my code clean. 
When I go to code which calls a function from a package and I try to "Go to Definition" in vscode, the tool tells me it cannot find the function.

To recreate the bug, I made the following simple workspace:
![image](https://user-images.githubusercontent.com/14311168/234919309-979ce9a2-61d1-4601-85f4-282debf1cd63.png)

For all the functions in het script, the "Go to Definition" works, except for the `package.function_in_package()` function.

When I do the same thing from matlab, it works and it can open the right function
![image](https://user-images.githubusercontent.com/14311168/234919938-830830e3-516b-4564-bd51-2fb9b8946247.png)

**Comment by SamReinsel** [comment]
I'm able to peek and go to definition inside my custom packages:
![image](https://user-images.githubusercontent.com/71461485/235739398-4af42df4-5bc9-4641-b41a-ed49d1648641.png)

Although my package itself is saved to my pathdef file so on any MATLAB startup it is automatically on the path

If i make a new package in a folder not on my default path and edit in in VSCode I get the same result as you did, unable to find definition
![image](https://user-images.githubusercontent.com/71461485/235740150-5acbc35d-67a0-41a8-95da-9cf8322ea05a.png)

So it seems to me that this is an issue of the headless MATLAB instance not having the opened folder on the path.

**Comment by SamReinsel** [comment]
And actually, if i move that second function into another folder, close VSCode, and open it again, it has not added my new folder `nonPack` to the path, so it does not see `customFunc`
![image](https://user-images.githubusercontent.com/71461485/235744328-d50151ca-bb68-48d3-b0ae-cc2ebcaf5491.png)

However if i just expand the `nonPack` folder in my explorer, it is able to find it again as the folder is now added to the path
![image](https://user-images.githubusercontent.com/71461485/235744476-cee8acc2-ed51-40af-807c-23fe629e9309.png)

Expanding my `testPack` package still doesn't get it on the path though: 
![image](https://user-images.githubusercontent.com/71461485/235744931-343361e0-a424-4f2e-b344-8d3e4602dd9b.png)

**Comment by dklilley** [comment]
Thank you for identifying this issue! We will look into this and try to reproduce on our end.

**Comment by dklilley** [comment]
This should be resolved in v1.1.1.
