### ISSUE TITLE
MATLAB has been closed. Some functionality might be unavailable.

### ISSUE THREAD

**Issue by moolawooda** [mathworks/MATLAB-extension-for-vscode#56]
**Describe the bug**
I keep getting the error message **MATLAB has been closed. Some functionality might be unavailable.**.

![图片](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/103896544/11f246d2-a440-4a96-9bf5-f787b6ae9bd0)

But in fact, I have set the MATLAB path just the same as what I get from `matlabroot` command in MATLAB. 

![图片](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/103896544/f672eac9-962d-4d91-bd7f-f09089d16621)
![图片](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/103896544/a9f059ea-e002-41ff-a4e8-4e35941599dc)

**Useful Information**
 - OS Version: Win11 x64 10.0.22621
 - VS Code Version: 1.82.1
 - MATLAB Version: R2023a 9.14.0.2206163

**Additional context**
Restart of computer/softwares not work.

**Comment by dklilley** [comment]
This is a known issue which is actively being investigated. This is captured in mathworks/MATLAB-language-server#10 as well as being discussed in #38.
