### ISSUE TITLE
Add breakpoints using dbstop

### ISSUE THREAD

**Issue by goldrik** [mathworks/MATLAB-extension-for-vscode#57]
I have been experimenting with a workflow which involves editing MATLAB files using vs code, then running them by calling the script through an open MATLAB command window (separate from vs code). 

Suppose you have a MATLAB script. You can add a breakpoint by using `dbstop`, like so
<img width="600" alt="Screenshot 2023-09-13 at 5 00 18 PM (3)" src="https://github.com/mathworks/MATLAB-extension-for-vscode/assets/8674612/b54b1c6f-8e13-45aa-82ee-d473440f7f81">

By running the script through the MATLAB command window, I get
<img width="400" alt="Screenshot 2023-09-13 at 5 00 35 PM (2)" src="https://github.com/mathworks/MATLAB-extension-for-vscode/assets/8674612/b5a80054-da3e-4b93-8d85-dbb542488d77">

Which creates a debug point here
<img width="600" alt="Screenshot 2023-09-13 at 5 00 35 PM (3)" src="https://github.com/mathworks/MATLAB-extension-for-vscode/assets/8674612/9d849fe0-6909-4580-a2ca-c3d0cb9dee48">

I feel like there could be functionality to add breakpoints this way (for now). Perhaps adding a breakpoint in vs code could automatically add the line `dbstop at [line number add 1] in [current file]`

I know there is work to integrate MATLAB debugging in vs code, but this could be a simple workaround for now. 

Edit: Apparently, the `keyboard` command may work better in this case. I have never tried this, but it could be a preferable alternative to the clunky dbstop line. Still, something to bind the add/remove debug point shortcut to this command would be great.

**Comment by dklilley** [comment]
I have marked this closed with the addition of debugging support in v1.3.0 of the extension. Please feel free to open a new issue if there is something which is not addressed.
