### ISSUE TITLE
Please upload it to open-vsx.org

### ISSUE THREAD

**Issue by PatrikN-work** [mathworks/MATLAB-extension-for-vscode#64]
To be able to use this in other binaries like [Theia ](https://theia-ide.org/)than VSCode it would be great if this can be uploded to open-vsx.org

**Comment by marcdumais-work** [comment]
open-vsx.org is the registry used by [VSCodium](https://github.com/VSCodium/vscodium) and probably other code-oss derivatives, as well as Theia applications.

See [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) for more information about publishing to `open-vsx.org`.

**Comment by dklilley** [comment]
We currently do not have any plans to publish the extension to the open-vsx marketplace, but may consider this in the future.

Take a look at #19 for a current workaround.
