### ISSUE TITLE
Highlight current section (%%)

### ISSUE THREAD

**Issue by dklilley** [mathworks/MATLAB-extension-for-vscode#69]
Splitting part of #8 into this feature request, as the other part of it has been resolved.

It would be great to have code sections highlighted similar to the MATLAB editor (or at least highlight the lines of code starting with %%).

**Comment by goldrik** [comment]
Just wanna +1 this issue. The lack of section highlighting on vscode reduces readability in my opinion, particularly for scripts which use sections as a way to delineate portions of a larger analysis pipeline.

**Comment by goldrik** [comment]
Code "sections" or "cells" can already be highlighted in python (using #%%), maybe sections on MATLAB could be highlighted in the same way (without the unnecessary text "Run Cell", "Run Below", etc). 
<img width="475" alt="Screenshot 2024-01-05 at 1 04 34 PM 2" src="https://github.com/mathworks/MATLAB-extension-for-vscode/assets/8674612/4a97f7b0-26d6-4e62-bcc4-d2371337d6f1">

**Comment by wohenbushuang** [comment]
> at least highlight the lines of code starting with %%

Though I made a duplicated issue #150 before, is there any updates on this issue?

**Comment by dklilley** [comment]
Unfortunately I do not have any updates at this time. However, this is still on our radar as functionality we would like to add!

**Comment by CalebAlberga** [comment]
I hate to be "that guy", but is there an option to _disable_ this? It's throwing off the rest of my code highlighting. Nice to see the extension is well-maintained with updates though.

**Comment by dklilley** [comment]
Hi @CalebAlberga, thanks for reaching out about this!

Currently, there is no setting to control this. Can you create a new issue for this? We would be happy to consider it for a future update!
