### ISSUE TITLE
Incorrect syntax highlighting of a comment on a while loop

### ISSUE THREAD

**Issue by cb0502** [mathworks/MATLAB-extension-for-vscode#72]
When writing a comment after an if condition, it is correctly recognized as a comment (syntax highlighting). However, on a while loop, this is not highlighted correctly.

Repro Code:
if condition %comment
end

while condition %comment
end

Screenshot:
![image](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/84457923/d91f0ed6-b8cc-4569-b71d-7783e59f5887)

**Comment by dklilley** [comment]
Thank you for reporting this!

This is being tracked separately by mathworks/MATLAB-Language-grammar#66
