### ISSUE TITLE
This extension keeps crashing and showing "MATLAB has been closed. Some functionality might be unavailable.

### ISSUE THREAD

**Issue by kimtaeyo** [mathworks/MATLAB-extension-for-vscode#74]
**Describe the bug**
Simply install this extension and open any MATLAB file, then it shows the following. Unofficial version of Xavier has never had any issue like this. 

**Screenshots**
![image](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/82065899/3390d628-df3f-4a44-a8a9-e5d085ad5944)

**Configuration**

![image](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/82065899/d6927f86-1cc8-469b-8399-0a16b78ab112)

**Useful Information**
 - MATLAB Version R2023b
 - OS Version: Windows 11 Enterprise 22H2 OS Build 22621.2428
 - VS Code Version: 1.83.3

**Comment by dklilley** [comment]
Thanks for reaching out about this! Here are a few things to try:
1. Does MATLAB launch normally on your machine?
2. Does running the `matlabroot` command in MATLAB return the same value that you have in the VS Code `installPath` setting? It looks like you currently have it set to `C:\MATLAB\R2023b` which is a non-standard install location, so I wanted to check.
3. Can you share any log files from the extension? The file location for these log files should be printed to the "MATLAB Language Server" log in the Output tab (Ctrl+Shift+U) in VS Code.

**Comment by kimtaeyo** [comment]
1. Yes.
2. Yes.
3. Log has been attached.
[matlabls_21140.zip](https://github.com/mathworks/MATLAB-extension-for-vscode/files/13300858/matlabls_21140.zip)

**Comment by dklilley** [comment]
Do you have a `startup.m` script? If so, can you share the contents or give a general description of what it is doing?

**Comment by kimtaeyo** [comment]
I don't have any user-defined startup script for MATLAB R2023b.

**Comment by dklilley** [comment]
We would like to look into this further. Can you reach out to support@mathworks.com and reference this issue? This will allow us to investigate further and avoid sharing more sensitive log files over GitHub.

**Comment by kimtaeyo** [comment]
Thanks but I don't want to spend too much time to file here and there. Also, I'm okay with using nonofficial extension from Xavier as of now since it has no issue at all. Hope you guys fix the issue soon.

**Comment by jecs** [comment]
I am having this issue on macOS Sonoma, @dklilley. 

Startup is the output of `matlabroot`. I have no custom `startup.m`. Version 2023b. I see that vscode is opening instances of Matlab on Activity Monitor, but these never "register" with vscode. Would it be OK to reopen this issue or should I open a new one?

**Comment by kimtaeyo** [comment]
I have used Matlab unofficial extension and there is zero issue so far for windows/mac.

**Comment by dklilley** [comment]
@jecs , can you please open a new issue and include a description of the behavior as well as the logs from the language server? The path to the log directory should be logged to the Output panel in VS Code.
