### ISSUE TITLE
Error while communicating with MATLAB

### ISSUE THREAD

**Issue by mrtnbrst** [mathworks/MATLAB-extension-for-vscode#76]
**Describe the bug**
Extension crashes on every occasion where a running MATLAB instance is required (MATLAB license available, MATLAB is also running with GUI at the same time)

**To Reproduce**
1. Start VSCode
2. Edit .m files
3. Crash of  MATLAB extension, which leads to intellisense, formatting and other features not working at any point

This description is very vague - what other information might be interesting / relevant?

**Expected behavior**
Should be able to use the features described in the README.

**Screenshots**
![2023-11-20 13_27_30-matlab not running](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/54993850/8e5f585a-be51-4864-920d-a9da903886b5)
![2023-11-20 13_27_54-matlab was closed](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/54993850/c9ad58d8-4c5e-4ffa-a456-456743f208c5)
![2023-11-20 13_28_28-matlab extension log within vscode](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/54993850/3d5bd0e3-cb04-44a6-b56e-f0bb1f0061f9)

**Useful Information**
VSCode:
Version: 1.84.2 (user setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0

OS: Windows_NT x64 10.0.19045
 - MATLAB 2022A
 - Extension version: v1.1.4

**Additional context**
Log files: 
[languageServerLog.txt](https://github.com/mathworks/MATLAB-extension-for-vscode/files/13414776/languageServerLog.txt)
[matlabLog.txt](https://github.com/mathworks/MATLAB-extension-for-vscode/files/13414778/matlabLog.txt)
[matlabls_conn.json](https://github.com/mathworks/MATLAB-extension-for-vscode/files/13414780/matlabls_conn.json)

VSCode settings:
![image](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/54993850/87abec96-ecdc-4bc2-8726-b3ba64bcfcfe)

**Comment by dklilley** [comment]
Thank you for reaching out about this! We have had trouble reproducing this ourselves, and would like your assistance to look into this further.

Can you reach out to support@mathworks.com and reference this issue? This will allow us to investigate further and avoid sharing more sensitive log files over GitHub.

**Comment by eric-dishman-ctct** [comment]
I was having a same issue today with the MATLAB language server. I recently changed the proxy environment variables. I noticed that I would get an error when trying to check for updates of VSCode. 

> net::ERR_PROXY_CONNECTION_FAILED

I deleted the proxy environement variables and restarted VSCode. After this, I can check for updates as well as connect to the MATLAB language server. 

Hope this helps.

**Comment by mrtnbrst** [comment]
> I was having a same issue today with the MATLAB language server. I recently changed the proxy environment variables. I noticed that I would get an error when trying to check for updates of VSCode.
> 
> > net::ERR_PROXY_CONNECTION_FAILED
> 
> I deleted the proxy environement variables and restarted VSCode. After this, I can check for updates as well as connect to the MATLAB language server.
> 
> Hope this helps.

Thanks for your reply. That's what I also found out after playing around with the http_proxy and https_proxy environment variables.

**Comment by jankap** [comment]
I do have the same issues, see also #38 
I assume it's a proxy issue. My company has to use ZScaler.

**Comment by mrtnbrst** [comment]
Update from the conversation with support@mathworks.com:
The  support ticket is still open, the responsible developer is currently looking at the issue.

**Comment by eric-dishman-ctct** [comment]
@mrtnbrst , One other thing that I have noticed is that if I delete my proxy environment variables. I have to restart my computer in order to get the extension to connect again. Can you pass that information along to the developer please? Thanks.

**Comment by eric-dishman-ctct** [comment]
Ah, yes I am on Windows. I'll try that next time. Thanks.

**Comment by wzh4464** [comment]
My apple silicon M1 have the same problem. I am not using any proxy.

**Comment by dklilley** [comment]
@wzh4464 , if you do not have a proxy set up, this may be a separate issue. Can you reach out to support@mathworks.com and request an escalation so we can look into this further?
