### ISSUE TITLE
NO_PROXY is not respected by extension

### ISSUE THREAD

**Issue by plwalsh** [mathworks/MATLAB-extension-for-vscode#78]
**Describe the bug**

In proxy-supported environments, the extension fails to establish a connection to MATLAB, because it is attempting to route its connection to `localhost` through your proxy host. The extension should be bypassing the proxy for connections to hosts specified in the `NO_PROXY` environment variable. However, including `localhost` on the bypass list has no effect.

**Related information**

It appears that the proxy support for extensions was expanded in 2019 to include support for `NO_PROXY`: https://github.com/microsoft/vscode/issues/68260.

**To Reproduce**

1. Set up a proxy server
2. Set your system environment variables to point to your proxy server
    - `HTTP_PROXY=http://proxy.company.com:3128`
    - `HTTPS_PROXY=http://proxy.company.com:3128`
3. Set your system environment variable to bypass the proxy for `locahost`
    - `NO_PROXY=localhost`
4. Launch VSCode in a MATLAB project workspace
5. Open a MATLAB script if needed
6. Watch the extension try to connect to MATLAB
    - ![image](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/43576448/de83ab7a-9fd3-45be-8815-a10a8eba4934)
7. See the popup message saying that it failed to connect
    - ![image](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/43576448/6c918ac9-cc8c-4f59-aa9e-6416d222b856)
    - ![image](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/43576448/58a83b22-6a76-4e78-9f60-c8d0234c21c3)

**Expected behavior**

The MATLAB extension should bypass the proxy and successfully establish its connection to localhost.

**Screenshots**

See above.

**Useful Information**

```
Version: 1.86.0-insider (user setup)
Commit: a017b12b9caa3475675cfe6fda014fcf5af388c9
Date: 2023-12-19T05:37:59.567Z
Electron: 27.1.3
ElectronBuildId: 25612240
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045
```

**Additional context**

I've already worked with MathWorks support on this issue and they acknowledge the deficiency. They told me they have opened up a formal request to address the problem; however, I wanted to open up this issue so that it is tracked publicly and viewable by all.

**Comment by meiswjn** [comment]
Hi,
we are facing the same issue. Is there any response from the maintainers already?
Thanks!

**Comment by dklilley** [comment]
This is an issue which we are looking into. Unfortunately, we do not have a workaround at this time beyond clearing the `HTTP_PROXY` and `HTTPS_PROXY` environment variables.
