### ISSUE TITLE
Feature request - Highlight sections, show in outline

### ISSUE THREAD

**Issue by Elgox2** [mathworks/MATLAB-extension-for-vscode#8]
Thanks for starting with the official support! 

A couple of features I'd like to see:

- It would be great to have code sections highlighted similar to matlab editor (or at least highlight the lines of code starting with %%)

- Having sections shown in outline would be also great help.

**Comment by dklilley** [comment]
Thanks for the suggestion!

An initial version of outline support is [already being implemented](https://github.com/mathworks/MATLAB-language-server/pull/1), but will not include sections. However, we do want to add support for those in the future as well!

**Comment by dklilley** [comment]
Sections have been added to the code outline in v1.1.4.

I am going to mark this issue as done, resolved by #68. 

Because this change does not include any highlighting of the sections, I have created #69 to capture that request separately so it is not lost.
