### ISSUE TITLE
Incorrect warnings / errors upon first connecting to MATLAB

### ISSUE THREAD

**Issue by goldrik** [mathworks/MATLAB-extension-for-vscode#84]
The MATLAB linter correctly identifies info, warnings, and errors for MATLAB files, shown below in this contrived example

<img width="632" alt="Screenshot 2024-01-11 at 12 58 00 PM (2)" src="https://github.com/mathworks/MATLAB-extension-for-vscode/assets/8674612/1c062de1-c6be-462b-8c1f-40b0bd7fe5aa">

However, upon connecting to MATLAB, the warnings get reloaded. They appear to be correct for the first file, but these warnings are identical for the rest of the files (incorrect). 

<img width="629" alt="Screenshot 2024-01-11 at 12 58 11 PM 2" src="https://github.com/mathworks/MATLAB-extension-for-vscode/assets/8674612/150d6d1b-dd47-41e5-bb98-093101ba0c62">

Currently, the way to "fix" this bug is by going through and manually saving every file again. 

I have seen this error on both Windows and Mac (Apple Silicon). 

Visual Studio Code 1.85.1
MATLAB r2023b, r2023a
MATLAB Extension v1.1.5

**Comment by dklilley** [comment]
I have been able to reproduce this on my end. Thanks for reporting!
