### ISSUE TITLE
Error in every MATLAB cell "Unable to run code analysis" in VS Code

### ISSUE THREAD

**Issue by tylerlekang** [mathworks/MATLAB-extension-for-vscode#88]
**System:**
Windows 10
Conda 23.5.0
Python 3.8.16
matlab-proxy 0.10.0
jupyter-matlab-proxy 0.10.1
Matlab R2023a Update 5

**Issue:**
If I open any existing notebook or make a new notebook and change the cell code type to Matlab, there is an error message displayed saying "Unable to run code analysis. 'file.ipynb' has an invalid file extension"

![issue](https://github.com/mathworks/jupyter-matlab-proxy/assets/20463434/9c2d177e-8ff3-463b-af6d-4e23bb97e6bf)

I have never seen this error before today. This error does not happen in regular editor windows for Matlab .m files, where analysis is run normally and is working fine.

I don't think any code analysis was actually done before in notebooks, but there wasn't an error message either. Really I think that Matlab VS Code extension was just applying the nice syntax highlighting to each cell, and that is still being done.

Possibly something has just been updated in the Matlab VS Code extension? I tried disabling it and re-enabling it, and the error comes right back. EDIT: it seems you cannot run Matlab code cells in VS Code without the Matlab VS Code extension installed and enabled.

I don't understand why they would want such errors to be raised?? Isn't it a perfectly valid use of their extension to run Matlab code in notebook cells?

**Comment by prabhakk-mw** [comment]
@tyePhDCandy, I'd recommend opening another issue on this repository with some detailed steps on how to reproduce the issue you are describing, which does seem significantly different from what @tylerlekang is reporting.

**Comment by tylerlekang** [comment]
Hi @dklilley @prabhakk-mw is there any update on this?

Naïve comment: isn't this just updating [something] so that .m *and* .ipynb won't throw this error?

Thank you!
