### ISSUE TITLE
Global search overwrites files.

### ISSUE THREAD

**Issue by hildebrandecon** [mathworks/MATLAB-extension-for-vscode#89]
**Describe the bug**

When using the MATLAB formatter, included in this extension, the global search function potentially overwrites files with each other's content. Also the compare selected files function has the same issue.

**To Reproduce**
1. Create a new folder with two `.m` files, having distinct content but containing one overlap (in my case, `randomNumber`). Open these files in split-view (not essential, but illustrates the problem perfectly)
2. Go to the global search-and-replace plugin of VS code and search for the overlap (`randomNumber`) and replace it everywhere by something else (`my number`). See first screenshot for pre clicking replace everywhere.
3. Instead of replacing just this term, one file gets overwritten entirely to the content of the other file. See second screenshot for post clicking replace everywhere.
4. The compare function has the same issue, see screenshot 3 pre changing something on the left. And the fourth screenshot for after changing something on the left before saving and the fifth for after saving.

**Expected behavior**
The search-and-replace should only replace the terms. The compare function should not affect the files at all.

**Screenshots**

![image](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/61334700/dc0fd956-2075-489d-bc7f-fed899cad4ed)

![image](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/61334700/823afe4e-6ae6-4070-b238-c985fa597841)

![image](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/61334700/86901de8-c612-4287-bb8e-360f92ca4a07)

![image](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/61334700/64ce2d7d-3569-4914-965a-a3a34aef97f9)

![image](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/61334700/e1f08414-fb9d-4dd9-961c-485adf5f47a1)

**Useful Information**
OS Version: macOS 14.2.1

VS Code Version: 

Version: 1.86.0 (Universal)
Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
Date: 2024-01-31T10:29:15.765Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.2.0

**Comment by dklilley** [comment]
Thank you for reporting this!

I am able to reproduce this - it appears that this only occurs when the "Format on Save" setting is enabled (in both of these cases, multiple files are being saved, and therefore formatted, simultaneously).

We will look into this issue.

**Comment by hildebrandecon** [comment]
Yes, agree! It only appears with Format on Save! Thanks for looking into it!

**Comment by dklilley** [comment]
This is resolved in v1.2.0 (#97)
