### ISSUE TITLE
cannot connect to MATLAB on mac os sonoma 14.2

### ISSUE THREAD

**Issue by yuchensun97** [mathworks/MATLAB-extension-for-vscode#93]
**Describe the bug**
MATLAB was unable to start. If MATLAB is installed, confirm that the MATLAB executable path setting is properly configured

**To Reproduce**
1. Go to 'vs code', open the workspace folder
2. Click on 'Connect to MATLAB'
3. Notification prompts: MATLAB was unable to start. If MATLAB is installed, confirm that the MATLAB executable path setting is properly configured

**Expected behavior**
VS Code should connect to MATLAB.

**Screenshot**
<img width="463" alt="image" src="https://github.com/mathworks/MATLAB-extension-for-vscode/assets/54690197/18c6fa8b-8430-434d-bb90-a80856099e76">

**Useful Information**
 - OS Version: mac os sonoma 14.2
 - VS Code Version: 1.86.2
 - MATLAB version: R2023b

**Additional context**
matlabroot: `Applications/MATLAB_R2023b.app`
<img width="458" alt="image" src="https://github.com/mathworks/MATLAB-extension-for-vscode/assets/54690197/5fe3a896-feed-4715-b528-525da61ebd18">

output log:
```
(12:12:10) matlabls: Launching MATLAB...
[Error - 12:12:10 PM] (12:12:10) matlabls - ERROR: Error launching MATLAB: spawn Applications/MATLAB_R2023b.app/bin/matlab ENOENT
[Error - 12:12:10 PM] (12:12:10) matlabls - ERROR: Error launching MATLAB: Error
[Error - 12:12:10 PM] (12:12:10) matlabls - ERROR: Error launching MATLAB: Error: spawn Applications/MATLAB_R2023b.app/bin/matlab ENOENT
    at Process.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(12:12:10) matlabls: MATLAB process terminated
```

**Comment by dklilley** [comment]
Thank you for reaching out with this issue!

I believe you are missing a leading `/` in your "Install Path" setting. I think the value returned by `matlabroot` in MATLAB should be `/Applications/MATLAB_R2023b.app`.

Does making this change enable MATLAB to launch?

**Comment by dklilley** [comment]
Hi @yuchensun97, I wanted to check back and see if the above suggestion resolved the issue you were running into?

**Comment by yuchensun97** [comment]
> /Applications/MATLAB_R2023b.app

Hi. Thank you. It works now.

**Comment by yuchensun97** [comment]
> Hi @yuchensun97, I wanted to check back and see if the above suggestion resolved the issue you were running into?

Hi @dklilley , now the VS Code can connect to MATLAB, but the MATLAB itself failed to launch.

**Comment by dklilley** [comment]
Can you provide a bit more info? Are you seeing any errors in VS Code? Does the status bar item go back to saying "MATLAB: Not Connected" or does it get stuck at "MATLAB: Establishing Connection"?

**Comment by yuchensun97** [comment]
> Can you provide a bit more info? Are you seeing any errors in VS Code? Does the status bar item go back to saying "MATLAB: Not Connected" or does it get stuck at "MATLAB: Establishing Connection"?

Hi. It's `MATLAB: CONNECTED`, but at the same time, the application MATLAB itself failed to launch.

**Comment by versionbayjc** [comment]
Remaining issue seems the same as https://github.com/mathworks/MATLAB-extension-for-vscode/issues/9?

**Comment by dklilley** [comment]
I believe @versionbayjc is correct. If VS Code is stating `MATLAB: Connected`, then MATLAB should have launched through the extension. This instance of MATLAB is not visible.

On Mac, there is currently a known issue (#9) which prevents launching a separate instance of MATLAB (i.e. via the dock) when MATLAB is connected in VS Code.

**Comment by dklilley** [comment]
Closing as a duplicate, based on the previous comment.
