### ISSUE TITLE
Matlab license does not release when closing vscode

### ISSUE THREAD

**Issue by HLuo90** [mathworks/MATLAB-extension-for-vscode#96]
Type: <b>Bug</b>

Matlab license does not release when closing vscode

Extension version: 1.1.6
VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:41:44.469Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 5850U with Radeon Graphics      (16 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.31GB (13.19GB free)|
|Process Argv|--crash-reporter-id d336f1c9-8222-4759-9048-6948aa1e6e1f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30959801
cppperfnew:30973185
d34g3935:30971562
edj9j583:30969295
fegfb526:30973843
ccp1r6:30958156
dsvsc020:30973508

```

</details>

**Comment by dklilley** [comment]
Hi @HLuo90 , can you please provide some additional information about this issue including:
1. Steps to reproduce the behavior
2. The expected behavior
3. Any errors you are seeing

**Comment by HLuo90** [comment]
Hi @dklilley 
Here is a screenshot:

![image](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/15884075/e3391936-cd41-4083-b627-211f0a1dbcad)

**Comment by dklilley** [comment]
Thanks for the clarification!

Can you confirm through the Task Manager if there is still a MATLAB instance running on your machine after closing VS Code?

**Comment by HLuo90** [comment]
Yes, it is still there, feel free to close this in favor of #61
