### ISSUE TITLE
Can't launch Simulink

### ISSUE THREAD

**Issue by gursoyha** [mathworks/MATLAB-extension-for-vscode#99]
Simulink refuses to launch.

simulink
Warning: Error using fileread
Could not open file C:\Users\USERNAME\AppData\Local\Temp\matlablsTmp-v0h0gc\cert.pem. No such file or directory.
Error in matlab.internal.cef.webwindow (line 197)
                cert = char(fileread(certLoc));

Error in matlab.internal.webwindow/createImplementation (line 327)
                implObj = matlab.internal.cef.webwindow(varargin{:});

Error in matlab.internal.webwindow (line 163)
            obj.impl = obj.createImplementation(varargin{:});

Error in sltemplate.internal.DialogWebBrowser/createWindow
Error in sltemplate.internal.DialogWebBrowser
Error in sltemplate.internal.GalleryBrowserFactory.create
Error in sltemplate.internal.GalleryController
Error in sltemplate.ui.StartPage
Error in sltemplate.ui.StartPage
Error in sltemplate.ui.StartPage/instance
Error in sltemplate.ui.StartPage/getInstance
Error in sltemplate.ui.StartPage/doShow
Error in sltemplate.ui.StartPage.showCustomView
Error in sltemplate.ui.StartPage>@()sltemplate.ui.StartPage.showCustomView('Start',[],varargin{:})
Error in sltemplate.ui.StartPage/showWithFallback
Error in sltemplate.ui.StartPage.show
In sltemplate.ui.StartPage.showWithFallback
In sltemplate.ui.StartPage.show

**Steps to reproduce the behavior:**

Type simulink into Matlab terminal on VsCode.

**Expected behavior**

I expect Simulink to work because the third party extension called "Matlab Interactive Terminal for Visual Studio Code" had no problem launching Simulink from VsCode.

**Useful Information**
 - OS Version: Windows 11
 - VS Code Version: 1.87
 - Matlab 2023b

**Comment by dklilley** [comment]
Thanks for reporting this! This is a known issue with launching separate standalone applications (like Simulink and App Designer) from the MATLAB extension for VS Code. We are working to resolve this.
